language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer update

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - phpunit --configuration tests/phpunit.xml

notifications:
  email:
    recipients:
      - me@klay.me
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#gleez"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
