language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - "composer self-update"
  - "composer install --prefer-source --no-interaction --dev"
  - cd tests

script: phpunit

notifications:
  email:
    recipients:
      - me@klay.me
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#gleez"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
    on_success: change
    on_failure: always
